### ISSUE TITLE
Extra characters "\x00" coming with each message from ISE

### ISSUE THREAD

**Issue by javahas** [cisco-pxgrid/pxgrid-rest-ws#1]
Extra characters "\x00" coming with each message from ISE, I have trim it 		
message = bytes.Trim(message, "\x00")
to be able to parse it.

**Comment by alei121** [comment]
The ending NULL is according to the STOMP specification:
  https://stomp.github.io/stomp-specification-1.2.html#STOMP_Frames
It denotes the end of the STOMP frame.

You can either use the Content-Length to read the content
or read until you see a NULL.
