### ISSUE TITLE
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1076)>

### ISSUE THREAD

**Issue by jorgebanegas** [cisco-pxgrid/pxgrid-rest-ws#12]
Installed the pxgrid certs and followed the steps for the session_subscribe.py file. 

"python session_subscribe.py -a ise26.homelab.sj.local -n ise26 -s /Users/jbanegas/Desktop/pxgrid-rest-ws-master/certs/ise26.homelab.sj.local_ise26.homelab.sj.local.cer"

Been stuck on this error for some time if someone can provide tips. I am running this on MacOs

**Comment by jorgebanegas** [comment]
when i run the same command without a virtual environment i get

urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1129)>

**Comment by ValeriiSudakov** [comment]
> when i run the same command without a virtual environment i get
> 
> urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1129)>

how did you solve it?
