### ISSUE TITLE
getAllSession filter

### ISSUE THREAD

**Issue by Dale71** [cisco-pxgrid/pxgrid-rest-ws#19]
There was a new commit to support server side filtering 

[Added filter usage for server side filtering](https://github.com/cisco-pxgrid/pxgrid-rest-ws/commit/7d40b4a3ef32a4d6b243843862ff17762866b522)

The documentation also mentions get all sessions call now supports a filter

POST [restBaseUrl]/getSessions

{
  "startTimestamp": ISO8601 Datetime (optional)
  "filter": JMESFilter for each session object (optional) (e.g. "nasIpAddress == '10.0.0.1'")
}

I'm unable to get our ISE instance (3.3.0.430) to filter the response

https://ise:8910/pxgrid/mnt/sd/getSessions

json post body:

{
    "filter": "nasIpAddress == 172.18.1.230"
}

returns a result set with session on other NAS IP addresses (I would expect there to only be results form the filtered IP

Am I using the endpoint url correctly?

Thanks

**Comment by alei121** [comment]
Actually, this is a new feature in upcoming ISE 3.4, so it is not available yet.
I updated the wiki to reflect the ISE version.

Your filter will need a single quote around the IP address.

Thanks

**Comment by Dale71** [comment]
Ah good to know. Now looking forward to another ISE upgrade.

Thanks for the info
